package pantry

const GRAINS = "grains"
const PASTA = "pasta"
const PROTEINS = "proteins"
const DAIRY = "dairy"
const FRUITS = "fruits"
const VEGETABLES = "vegetables"
const CANNED_GOODS = "canned goods"
const BAKING = "baking"
const SPICES = "spices"
const OILS = "oils"
const VINEGARS = "vinegars"
const CONDIMENTS = "condiments"
const SNACKS = "snacks"
const SWEETS = "sweets"
const BEVERAGES = "beverages"
const DRIED = "dried"
const MISCELLANEOUS = "miscellaneous"
