// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package database

import (
	"database/sql"
	"time"
)

type Pantry struct {
	ID       string
	UserID   string
	ItemName string
	Quantity int64
	AddedAt  string
	ExpiryAt string
}

type User struct {
	ID           string
	Name         string
	PasswordHash string
	CreatedAt    time.Time
	UpdatedAt    time.Time
	IsAdmin      sql.NullInt64
}
