// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: pantry.sql

package database

import (
	"context"
)

const addItem = `-- name: addItem :one
INSERT INTO pantry (
    id, user_id, item_name, quantity, added_at, expiry_at
) VALUES (
    ?, ?, ?, ?, strftime('%Y-%m-%d','now'), ?
)
RETURNING id, user_id, item_name, quantity, added_at, expiry_at
`

type addItemParams struct {
	ID       string
	UserID   string
	ItemName string
	Quantity int64
	ExpiryAt string
}

func (q *Queries) addItem(ctx context.Context, arg addItemParams) (Pantry, error) {
	row := q.db.QueryRowContext(ctx, addItem,
		arg.ID,
		arg.UserID,
		arg.ItemName,
		arg.Quantity,
		arg.ExpiryAt,
	)
	var i Pantry
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ItemName,
		&i.Quantity,
		&i.AddedAt,
		&i.ExpiryAt,
	)
	return i, err
}
