name: Deployment

on:
  pull_request:
    branches: [main]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    env:
      DATABASE_URL: ${{ secrets.DATABASE_URL }}

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.24.2"
    
      - name: Install goose
        run: go install github.com/pressly/goose/v3/cmd/goose@latest    
      
      - name: Migrate DB
        run: | # database is saved in data folder, so we need to create it
          mkdir data
          chmod +x ./scripts/migrate_up.sh && ./scripts/migrate_up.sh

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Build .env file
        # This will be decomissioned, it's needed now 
        run: |
            echo "PORT=${{ secrets.PORT }}" > .env
            echo "DATABASE_URL=${{ secrets.DATABASE_URL }}" >> .env
            echo "JWT_SECRET=${{secrets.JWT_SECRET}}" >> .env

      - name: Build Docker Image
        run: docker build --tag mrramonster/pantry_pal:latest .

      - name: Publish Docker Image
        run: |
         docker login -u mrramonster -p ${{ secrets.DOCKER_HUB_TOKEN }}
         docker push mrramonster/pantry_pal:latest