name: CD

on:
  pull_request:
    branches: [main]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.24.2"
    
      - name: Install goose
        run: go install github.com/pressly/goose/v3/cmd/goose@latest    
      
      - name: Migrate DB
        run: |
          mkdir data
          chmod +x ./scripts/migrate_up.sh && ./scripts/migrate_up.sh

      - name: Build Docker Image
        run: docker build --tag mrramonster/pantry_pal:latest .