name: Deployment

on:
    push:
      branches: [main]

jobs:
  tests:
    name: Deploy
    runs-on: ubuntu-latest

    env:
      DATABASE_URL: ${{ secrets.DATABASE_URL }}

    steps:
    - name: Check out code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: "1.24.2"
    
    - name: Install goose
      run: go install github.com/pressly/goose/v3/cmd/goose@latest    
    - name: Migrate DB
      run: chmod +x ./scripts/migrate_up.sh && ./scripts/migrate_up.sh
    
    - name: Build Docker image
      run: docker build --tag pantry_pal:latest .