name: CD

on:
  push:
    branches: [main]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Login Docker
        uses: docker/login-action@v3
        with:
            username: mrramonster
            password: ${{ secrets.DOCKER_HUB_TOKEN }}
        
      - name: Build and push Docker image
        id: push
        uses: docker/build-push-action@v6
        with:
            context: .
            file: Dockerfile
            push: true
            tags: mrramonster/pantry_pal:latest
